# Generated by Django 3.0.8 on 2020-11-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='movie name')),
                ('duration', models.FloatField(verbose_name='movie duration')),
                ('ratings', models.FloatField(verbose_name='movie rating')),
            ],
        ),
    ]
