# Generated by Django 3.0.8 on 2020-11-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='ratings',
            new_name='rating',
        ),
    ]
