# Generated by Django 3.0.8 on 2020-11-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/default/default_img.jpg', upload_to='images/'),
        ),
    ]
