# Generated by Django 3.0.8 on 2020-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.nLDShz9SB5YleA3GH5fJJAHaHa?pid=Api&rs=1', max_length=500),
        ),
    ]
